### PR TITLE
Adds additional options fixes #14

### LINKED ISSUE #14: Anonymus functions are not handled correctly
```julia
"""
    foo(bar = (x->begin

DOCSTRING

# Arguments:
- `bar::Function`: DESCRIPTION
"""
function foo(bar::Function=x->x)

end
```

### PR DESCRIPTION
**Pull request by ValentinKaisermayer**
Adds options for more fain-grain control over the stuff that is in the description.

### CODE REVIEW

**Comment by ValentinKaisermayer** [comment]
fixes #14 
Is simply not printed

**Comment by baggepinnen** [comment]
Very nice, thanks for adding :) 
We could mention the extra options in the readme under [options](https://github.com/baggepinnen/AutomaticDocstrings.jl#options) as well

**Comment by baggepinnen** [comment]
Should we perhaps have tests for the new options that introduce new logic, like `kwargs_header` and the various `defaults_in_...`?

**Comment by baggepinnen** [comment]
Very nice, thank you :)

**Pull request merged**
